### ISSUE TITLE
[BUG]: Extension does not appear to work on macOS Ventura

### ISSUE THREAD

**Issue by spkane** [AykutSarac/jsoncrack-vscode#10]
### Issue description

Three separate people have installed this extension on various macOS systems, and when they open a JSON file and click on the icon for JSON Crack, it simply opens up a blank page, usually with no error, although once I was able to get this:

`Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..`

I have no idea if this impacts other systems, but it appears to be impacting multiple macOS installs.

### Media & Screenshots

![bug](https://user-images.githubusercontent.com/129629/200906349-afce6166-ad1d-4fbf-b6ca-5c4b432ceb73.jpg)

### Operating system

- OS: [e.g. iOS]: macOS 13.0
- Browser [e.g. chrome, safari]: vscode (chrome, safari, and firefox are all on the system)
- vscode: 1.73.0

### Priority this issue should have

High (immediate attention needed)

**Comment by viniciusmoreiraa** [comment]
It worked perfectly on macOS, I noticed that since I updated my macOS to Ventura version 13.0, it no longer works.

vscode:
Version: 1.73.1 (Universal)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T02:08:38.961Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.1.0
Sandboxed: No

**Comment by spkane** [comment]
@rsalmond @dginther Were both of you on macOS 13.0 (Ventura) as well?

**Comment by rsalmond** [comment]
I'm on 12.6 Monterey.

**Comment by AykutSarac** [comment]
Please let me know if it works now.

**Comment by haiming12138** [comment]
The extension seems to be functioning now. I'm on 13.0.1 Ventura.

**Comment by Finkman** [comment]
Seems to be the same as my issue #11

**Comment by rsalmond** [comment]
👍  sorted for me too, thanks @AykutSarac !

**Comment by spkane** [comment]
So, I finally had a moment to test this, and I don't see the error anymore, and I am getting a grid in the view window, but I still am not seeing of the JSON node visualizations.

![CleanShot 2022-12-02 at 10 09 34](https://user-images.githubusercontent.com/129629/205358343-ca76341b-f4df-4d1b-910c-8fe23b6585bb.png)

**Comment by jarojetu** [comment]
Hi, Im having the same issue on Win10, VSC: 1.75.1, Extension verions: 1.0.8.

I can see only black sreen with empty grid - no error message.

**Comment by AykutSarac** [comment]
Merging under #29
