### ISSUE TITLE
Publish package on https://open-vsx.org/ (VScodium/Gitpod/Eclipse Theia/etc.)

### ISSUE THREAD

**Issue by arthurzenika** [AykutSarac/jsoncrack-vscode#15]
### Feature

I'd love to use this project, but as a user of https://vscodium.com/ which in turn uses https://open-vsx.org/ for its extensions I can't install it easily. 

### Alternative solutions or implementations

Could you maybe publish the VSIX package on github ?

**Comment by tomByrer** [comment]
+1

Protip:
1. close Codium
2. Open VSCode
3. Install Extension in VSCode
4. open your VSCode's `extensions.json` (found in `~/.vscode`) & copy the entry for the extension you want to use
5. open your VSCodium `extensions.json` & paste there; watch out for trailing commas
6. Open VSCodium & enjoy!

![image](https://user-images.githubusercontent.com/1308419/213945261-2af66961-da58-45dc-8d9a-74f8f77b9454.png)

**Comment by erlefloch** [comment]
@arthurzenika I would suggest to rename this issue "Publish package on https://open-vsx.org/" because it also relevant for users of Gitpod or Eclipse Theia for example.

**Comment by AykutSarac** [comment]
Merging under #29
