### ISSUE TITLE
How can I use this extension

### ISSUE THREAD

**Issue by NunoTrigo1986** [AykutSarac/jsoncrack-vscode#16]
### Issue description

Hi,

I ve installed this extension on vscode. My question is how can I use it. When I click on a random json file, the text editor that opens is the normal one. Further I can not see this extension on the left bar where my other extensions are. 

Could somebody help med ? thanks!

### Operating system

- OS: [e.g. iOS]:
- Browser [e.g. chrome, safari]:

- Any other details...

### Priority this issue should have

High (immediate attention needed)

**Comment by jonolave** [comment]
I also miss a quick intro on how to use the extension.

**Comment by CosminVana** [comment]
I am confused as well. Just downloaded the extension. The editor is the same.

**Comment by CosminVana** [comment]
I've found a way to start it. You have to use Command Pallete. Seems to work ok.

![image](https://user-images.githubusercontent.com/25432851/211662014-f1ffa0ef-e0d2-4f31-b937-8577efb6ded0.png)

**Comment by tomByrer** [comment]
Yes, `[F1]` then search for `crack`
Once you use it, it will be up top of list.

**Comment by AykutSarac** [comment]
Merging under #29

**Comment by AykutSarac** [comment]
Documentation has been added now, thanks for the feedback.
