### ISSUE TITLE
Would you consider publishing react components you use in this project to npm?

### ISSUE THREAD

**Issue by usirin** [AykutSarac/jsoncrack-vscode#17]
### Feature

I think this is a great product, and thank you so much for the effort you've put into this. I've been building a widget viewer for react components over at https://github.com/kamp-us/monorepo/pull/216 and i've been looking for a detailed json viewer to use in my experimental widget viewer.

I'd really love to be able to use https://github.com/AykutSarac/jsoncrack-vscode/blob/master/src/components/Graph/index.tsx in my widget viewer if this was a separate package.

I, and my community are ready to help in anyway we can.

### Other context

Here is a simple ugly json viewer i am currently hacking with 😅 

![image](https://user-images.githubusercontent.com/1783869/209724746-474c2579-6939-43b9-aef9-54c21eb35235.png)

**Comment by AykutSarac** [comment]
Hi, thanks for your interest and offer. JSON Crack and its components gets updated continuously, thus it makes harder to create a stable graph component without having breaking changes and requires a detailed planning and roadmap. I have plans for this in the future but at the moment I'm focused on improving https://jsoncrack.com/embed which is more effective than a component specific for React. Maybe that's what you need.

**Comment by AykutSarac** [comment]
Hello @usirin, currently I'm exporting the graph as a React component to release it as npm package. I'd love to hear if would like to contribute for it 🙂

**Comment by AykutSarac** [comment]
Merging under #29

**Comment by AykutSarac** [comment]
Published at [npm](https://www.npmjs.com/package/jsoncrack-react) but not officially announced yet, open to feedbacks though.
