### ISSUE TITLE
[BUG]: Not compatible with Vscode version 1.70.0

### ISSUE THREAD

**Issue by AndrewLaganaro** [AykutSarac/jsoncrack-vscode#18]
### Issue description

I've tried to install but Vs code says it is not compatible with my Vs code version 1.70.0
![image](https://user-images.githubusercontent.com/45211616/210156062-3ef04026-fc19-4f11-a695-51ac4b931e9a.png)

### Operating system

- OS: Windows 10

### Priority this issue should have

High (immediate attention needed)

**Comment by embedvr** [comment]
+1, not sure if 1.17.0 is too up to date or too old for JSON Crack, however 1.17.0 is the latest version I am able to get from my package manager (Fedora 37, Using DNF and the official VS Code repo)

According to [VS Code docs](https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions) it should be normal to be out of date with recent releases.
> Due to the manual signing process and the system we use to publish, the yum repo may lag behind and not get the latest version of VS Code immediately.

**Comment by AykutSarac** [comment]
Merging under #29

**Comment by AykutSarac** [comment]
Should be compatible with versions starting with 1.63.0 and beyond.
