### ISSUE TITLE
[BUG]: No Save/Download option with VSCode

### ISSUE THREAD

**Issue by aaron-ballard-530** [AykutSarac/jsoncrack-vscode#24]
### Issue description

There is no option to save the rendered mapping with the VSCode Extension.  The Save and SaveAs do not seem to have any connection with the generated diagram

### Operating system

Version: 1.75.1
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:34:59.000Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No

### Priority this issue should have

Low (slightly annoying)

**Comment by AykutSarac** [comment]
Merging under #29
