### ISSUE TITLE
JSON crack not showing graph sometime untill you restart

### ISSUE THREAD

**Issue by MosesWangira** [AykutSarac/jsoncrack-vscode#27]
Type: <b>Bug</b>

open any json sometimes it shows sometimes it doesnt untill a restart is done

Extension version: 1.0.8
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:47:05.613Z)
OS version: Linux x64 5.19.0-41-generic snap
Modes:
Sandboxed: Yes

**Comment by AykutSarac** [comment]
Merging under #29
