### ISSUE TITLE
Is this app avaliable with VS Code version 1.70.2?

### ISSUE THREAD

**Issue by NasonZ** [AykutSarac/jsoncrack-vscode#28]
### Feature

I can't download this extension from the vs code extensions marketplace, I get the errors saying `"it's not compatible with the current version of Visual Studio Code (1.70.2)"`. 

Are there any plans to resolve this? 

### Other context

I'm willing to do the adjustments if you can help plan what needs doing.

**Comment by AykutSarac** [comment]
Merging under #29

**Comment by AykutSarac** [comment]
Now available for versions 1.63.0 and beyond.
