### ISSUE TITLE
[BUG]: Can't run - You d'ont have an extension for debugging JSON message

### ISSUE THREAD

**Issue by mirekua** [AykutSarac/jsoncrack-vscode#31]
### Issue description

I install jsoncrack-vscode extension. When i try to run it on .json file i see this message - You d'ont have an extension for debugging JSON message

What i have to do ?

### Operating system

- OS: [e.g. iOS]:
- Browser [e.g. chrome, safari]:

- Any other details...

### Priority this issue should have

Low (slightly annoying)

**Comment by mirekua** [comment]
O I found. It have to do through vscode commands palette. Not F5. But the instructions of the extension are not correct

**Comment by AykutSarac** [comment]
Documentation is indeed bad right now, I'm planning an update to fix them all sorry about that. The orange icon at top right is for JSON Crack.

<img width="181" alt="image" src="https://github.com/AykutSarac/jsoncrack-vscode/assets/47941171/0dc02c36-69e9-41dc-835a-451004fb2a73">
