### ISSUE TITLE
Feature request: Rotate visualization

### ISSUE THREAD

**Issue by rubendinho** [AykutSarac/jsoncrack-vscode#5]
### Feature

Currently, it does not seem possible to rotate the visualization like in the Editor.  

In particular, the default view orients data left-to-right.  If you're using a vertical sidepanel and a deep JSON object, the visualization will fit the pane much better with a top-down orientation.

**Comment by mattseaboard** [comment]
+1 for requesting this feature.

**Comment by AykutSarac** [comment]
Merging under #29
