### ISSUE TITLE
[BUG]: Not able install extension in VS code (ver-1.70.1)

### ISSUE THREAD

**Issue by moneybharathe22** [AykutSarac/jsoncrack-vscode#7]
### Issue description

Can't install 'aykutsarac.jsoncrack-vscode' extension because it is not compatible with the current version of Visual Studio Code (version 1.70.1).

### Operating system

- OS: [e.g. iOS]:
- Browser [e.g. chrome, safari]:

- Any other details...
MAC

### Priority this issue should have

Medium (should be fixed soon)

**Comment by AykutSarac** [comment]
Hello, have you updated your VS Code version?

**Comment by focmb** [comment]
Hi,

same problem here. Can't install the extension with vs code 1.69 insider. The error message: not compatible with the current version of Visual Studio Code - Insiders (Version 1.69.0-insider)

**Comment by moneybharathe22** [comment]
Hey Guys

Please update vs code extension, I’m able to see the visualise Json.

Thanks
Mani

**Comment by AykutSarac** [comment]
Merging under #29

**Comment by AykutSarac** [comment]
Now available for versions 1.63.0 and beyond.
